name: format-lint

on: push

jobs:
  format-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/setup-uv@v8.1.0
      with:
        enable-cache: true
    - name: Set up Python
      run: uv python install
    - name: Setup
      run: uv sync --extra dev --frozen
    - name: Format with black and isort
      run: make format
    - name: Lint with flake8, mypy and pylint
      run: make lint
