name: format-lint

on: push

jobs:
  format-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: astral-sh/setup-uv@v8.2.0
      with:
        enable-cache: true
    - name: Set up Python
      run: uv python install
    - name: Setup
      run: uv sync --extra dev --frozen
    - name: Format with Ruff
      run: make format
    - name: Lint with Ruff and ty
      run: make lint
