name: unittest

on: push

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: astral-sh/setup-uv@v8.2.0
      with:
        enable-cache: true
    - name: Set up Python
      run: uv python install
    - name: Setup
      run: uv sync --extra dev --frozen
    - name: Run unit tests
      run: make utest
